#### Ques 1. Create a vector with values ranging from 10 to 49 


In [4]:
import numpy as np
v = np.arange(10,49)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### Ques 2.  Reverse a vector (first element becomes last)


In [5]:
import numpy as np
v = np.arange(10,49)
v = v[::-1]
print(v)

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


####  Ques 3.Create a 3x3 identity matrix

In [12]:
import numpy as np
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Ques 4. Create a 10x10 array with random values and find the minimum and maximum values

In [18]:
import numpy as np
x = np.random.random((10,10))
print(x)

[[0.44134385 0.98191912 0.52937793 0.93595713 0.71660636 0.62446145
  0.24981238 0.94265259 0.37643525 0.8681789 ]
 [0.14733923 0.18873419 0.87985181 0.30941211 0.24087091 0.50122453
  0.51010285 0.74353346 0.11787587 0.24837649]
 [0.88232938 0.23380604 0.32880916 0.3845032  0.51794619 0.8340679
  0.66400893 0.7817383  0.99732755 0.15713869]
 [0.06206898 0.84237939 0.99561423 0.63888598 0.70264002 0.57252298
  0.1294049  0.88560079 0.95257496 0.64032739]
 [0.30010528 0.23827214 0.00956591 0.84674976 0.96294418 0.38796585
  0.31545104 0.29338391 0.9253576  0.42098959]
 [0.64830326 0.33546991 0.11462771 0.06099573 0.75548617 0.31871263
  0.36508455 0.68273737 0.79170784 0.46786255]
 [0.79770807 0.4826613  0.89890004 0.44043408 0.48106666 0.69111981
  0.50483869 0.03208825 0.95221187 0.53589629]
 [0.69360362 0.42087388 0.40766554 0.28892505 0.48708463 0.31930228
  0.36371767 0.25726617 0.36238775 0.9428872 ]
 [0.08389994 0.35012616 0.89996023 0.04966525 0.88688222 0.19952153
  0.12818176 

#### Ques 5.What is the result of the following expression?
#### 0 * np.nan
#### np.nan == np.nan
#### np.inf > np.nan
#### np.nan - np.nan
#### np.nan in set([np.nan])
#### 0.3 == 3 * 0.1


In [19]:
0 * np.nan

np.nan == np.nan

np.inf > np.nan

np.nan - np.nan

np.nan in set([np.nan])

0.3 == 3 * 0.1

False

#### Ques 6.How to sum a small array faster than np.sum? 

In [21]:
Z = np.arange(10)
np.add.reduce(Z)

45

#### Ques 7.How to find the closest value (to a given scalar) in a vector?

In [32]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

86
